# Dockerfile — debian/bookworm, НЕ оптимізований (для порівняння в дослідницькій частині)
FROM python:3.12-bookworm

WORKDIR /app

# requirements.txt і код копіюються разом — при зміні коду
# pip install запускається заново (неефективно)
COPY app/ .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["python", "app.py"]
CMD ["--host", "0.0.0.0", \
     "--port", "8000", \
     "--db-host", "db", \
     "--db-name", "mywebapp", \
     "--db-user", "mywebapp", \
     "--db-password", "mywebapp_pass"]
